project:
  type: website
  output-dir: site
  preview:
    port: 4200
website: 
  title: "The Data Dive"
  favicon: favicon.ico
  google-analytics: "G-7YKVK73EZ4"
  cookie-consent: 
    type: implied
    style: simple
    palette: light
  description: |
    All of my wandering interests, semi-dilettantish data ponderings, and writings are collected for the public here.
  site-url: https://duncangates.me/blog/site/
  open-graph: true
  search: 
    show-item-context: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Blog"
        href: blog.qmd
      - text: "Art"
        href: art.qmd
      - text: "Maps"
        href: maps.qmd
      - text: "Web Apps"
        href: apps.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dungates/
format:
  html:
    theme: 
      light: [journal, theme-light.scss]
      dark: [journal, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual
