---
title: "Art"
output:
  distill::distill_article:
    css: "strapless.css"
---

```{r echo = F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
library(bs4cards)
library(dplyr)
generative_files <- list.files("art/generative") %>%
  tibble::as_tibble() %>%
  mutate(title = stringr::str_to_title(stringr::str_remove(value, ".png")),
         link = paste0("https://raw.githubusercontent.com/dungates/dungates.github.io/master/_art/generative/", value),
         image = paste0("https://raw.githubusercontent.com/dungates/dungates.github.io/master/_art/generative/", value)
         )
maps_files <- list.files("art/maps") %>%
  tibble::as_tibble() %>%
  mutate(title = stringr::str_to_title(stringr::str_remove(value, ".png")),
         link = paste0("https://raw.githubusercontent.com/dungates/dungates.github.io/master/_art/maps/", value),
         image = paste0("https://raw.githubusercontent.com/dungates/dungates.github.io/master/_art/maps/", value)
         )
recreation_files <- list.files("art/recreations") %>%
  tibble::as_tibble() %>%
  mutate(title = stringr::str_to_title(stringr::str_remove(value, ".png")),
         link = paste0("https://raw.githubusercontent.com/dungates/dungates.github.io/master/_art/recreations/", value),
         image = paste0("https://raw.githubusercontent.com/dungates/dungates.github.io/master/_art/recreations/", value)
         )
```


# Generative Art

```{r}
generative_files %>%
  cards(
    title = title,
    link = link,
    image = image,
    layout = "label-below"
  )
```


# Maps

```{r}
maps_files %>%
  cards(
    title = title,
    link = link,
    image = image,
    layout = "label-below"
  )
```


# Recreations

```{r}
recreation_files %>%
  cards(
    title = title,
    link = link,
    image = image,
    layout = "label-below"
  )
```

